lang_dict={
    'en':{
        'Streamlit Data Analysis --β Version--':'Streamlit Data Analysis --β Version--',
        'Regression Analysis':'Regression Analysis',
        'CSV file upload (please use organized data)':'CSV file upload (please use organized data)',
        'Use sample data : wooldridge(wage1)':'Use sample data : wooldridge(wage1)',
        'Data preview':'Data preview',
        'Select variable for analysis\n(Numerical data only)':'Select variable for analysis\n(Numerical data only)',
        'explained variable':'explained variable',
        'Explanatory variable':'Explanatory variable',
        'Number of parameters : ':'Number of parameters : ',
        'use robust standard errors':'use robust standard errors',
        'Logarithmic transfomation':'Logarithmic transfomation',
        'Result':'Result',
        'Correlation coefficient matrix display':'Correlation coefficient matrix display',
        'Estimation Result Details':'Estimation Result Details',
        'Using robust standard errors':'Using robust standard errors',
        'About statsmodels:\nhttps://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.RegressionResults.html':'About statsmodels:\nhttps://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.RegressionResults.html',
        'Valid only for numerical data or Missing values and zeros cannot be logarithmized':'Valid only for numerical data or Missing values and zeros cannot be logarithmized',
        'Please enter variables':'Please enter variables',
        'Please upload your data.':'Please upload your data.',
        'Feedback and Opinion':'Feedback and Opinion'
    },
    'ja':{
        'Streamlit Data Analysis --β Version--':'Streamlit データ分析--試用版--',
        'Regression Analysis':'回帰分析',
        'CSV file upload (please use organized data)':'CSVファイルアップロード(整理されたデータで使用してください)',
        'Use sample data : wooldridge(wage1)':'サンプルデータの使用 : wooldridge(wage1)',
        'Data preview':'データのプレビュー',
        'Select variable for analysis\n(Numerical data only)':'変数の選択(数値データのみ)',
        'explained variable':'被説明変数',
        'Explanatory variable':'説明変数',
        'Number of parameters : ':'パラメーター数 : ',
        'use robust standard errors':'頑健標準誤差を使用する',
        'Logarithmic transfomation':'対数変換をする',
        'Result':'結果',
        'Correlation coefficient matrix display':'相関行列の表示',
        'Estimation Result Details':'推定結果の詳細',
        'Using robust standard errors':'頑健標準誤差の使用',
        'About statsmodels:\nhttps://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.RegressionResults.html':'statsmodelsについて:\nhttps://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.RegressionResults.html',
        'Valid only for numerical data or Missing values and zeros cannot be logarithmized':'数値データのみ有効です。また欠損値やゼロは対数化不可です',
        'Please enter variables':'変数を入力してください',
        'Please upload your data.':'データをアップロードしてください',
        'Feedback and Opinion':'感想・意見はこちら'
    }
}
